name: Build and deploy a container to an Azure Container Registry

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Login to azure
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWRD }}
          
      - name: Build the container
        run: |
            docker build -f Dockerfile.prod \
            -t ${{secrets.ACR_SERVER}}/settled-client:${{ github.sha }} \
            -t ${{secrets.ACR_SERVER}}/settled-client:latest \
            .
            

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Container Registry
        run: |
            docker push ${{secrets.ACR_SERVER}}/settled-client:${{ github.sha }}
            docker push ${{secrets.ACR_SERVER}}/settled-client:latest
