name: Build and deploy a container to an Azure Container Registry

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build the application
      - uses: azure/docker-login@v2
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
     
      - run: |
            docker build . \
            -t ${{secrets.ACR_SERVER}}/.settled-client:${{ github.sha }} \
            -t ${{secrets.ACR_SERVER}}/.settled-client:latest \
            Dockerfile.prod

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Container Registry
        run: |
            docker push ${{secrets.ACR_SERVER}}/.settled-client:${{ github.sha }}
            docker push ${{secrets.ACR_SERVER}}/.settled-client:latest
