name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: azure/docker-login@v2
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}

      - name: Build the application
      - run: |
            docker build . \
            -t ${{secrets.ACR_SERVER}}/.settled-client:${{ github.sha }} \
            -t ${{secrets.ACR_SERVER}}/.settled-client:latest \
            Dockerfile.prod

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Azure Container Registry
        run: |
            docker push ${{secrets.ACR_SERVER}}/.settled-client:${{ github.sha }}
            docker push ${{secrets.ACR_SERVER}}/.settled-client:latest
